<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
    'THUMB_URL'        => "/assets/gallery/thumb/",
    'DEST_PATH'         =>"../public/assets/gallery/",
    'GALLERY_URL'      =>  url('/gallery'),


);
