<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
    /*URLs used accross the app*/
    'THUMB_URL'        => "/assets/gallery/thumb/",
    'DEST_PATH'         =>"../public/assets/gallery/",
    'GALLERY_URL'      =>  asset('/gallery'),
    
    /*The webmasters email*/
    'WEBMASTER_@'  => "aguilaw@hedron.com",


);
