<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
    /*URLs used accross the app*/
    'THUMB_URL'        =>'/assets/gallery/thumb/',
    'DEST_PATH'         =>'/assets/gallery/',
    'GALLERY_URL'      =>  action('PagesController@ShowHome')."/gallery/",
     'SKETCHBOOK_URL'      =>  action('PagesController@ShowHome')."/sketchbook/",
     'HOME_URL'      =>  action('PagesController@ShowHome'),
    
    /*The webmasters email*/
    'WEBMASTER_@'  => "aguilaw@hedron.com",


);
